### PR TITLE
Full refactory & working with pure JS

### PR DESCRIPTION
**Pull request by WrathChaos**
First of all, thank you so much @fabio-alss-freitas for this awesome library :)

Here are what I've done:
- [x] It is not Expo dependable now. 
- [x] It works both Expo and Pure React Native now.
- [x] Customizable background image feature. (Finally)
- [x] I refactored and changed the logic a bit. It should work the same thing as the old one. 
- [x] I also refactored the styling code.
- [x] Added a fully working example project.

Waiting for the PR merging :)  Really need this PR for my pure react native project :)

### CODE REVIEW

**Comment by WrathChaos** [comment]
Until this pr is merged, everyone can use this PR with this branch:
`npm i @freakycoder/react-native-animated-splash-screen`

**Comment by fabio-alss-freitas** [comment]
Thank you very much for your contribution @WrathChaos !

**Comment by WrathChaos** [comment]
@fabio-alss-freitas When can you publish a new version? Also, if you want I can be a maintainer of this library as well :)

**Comment by fabio-alss-freitas** [comment]
> @fabio-alss-freitas When can you publish a new version? Also, if you want I can be a maintainer of this library as well :)

It is already published!
That will be cool!

**Pull request merged**
